sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "choi15ho@gmail.com"
  - git config --global user.name "YouKnowGit"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "GpHaKzJuWhci+La+pUrWG5SlZuPCwMGEv5gpPcXgEOu+CplbNZXli0vY47Zr88JtTYChvnhh89MiG7/imiN2XxfBzmevFOpQHsQUOJdTtdv0fkvKVvkfcbTIMzIe0kZdbDohfYj7FMew2lF/0Zi4cgikWEPCIiXV3XEfbTrofn3srJ2WCK7n82CqIvaUi+vdjLXncXLxMcJgtWopQeunq7Zv7c0J9TqxvNTzjhKil3shYaCkjkKExLpcZ/RQd4QoNNXfyWu/qpodkOB2dms9ZQCvKuPhudCMgDH3DoN3SHH9M60WAq65KA25LcN2q89MtwnM5x9HtCkSif9PeQ5ZYx9nvnLcoTVI/Fif4dSXMJTjdRSRiBQO3hkT5IuiC+Y1hE0iiGwnY8NC357e6m4eBGPaOYtF04+FNI7J58bzkAAuQUh1L9D8TVCB2FD9AtIcS2nei0l90jf7Z2Zx8nhMopZnkgqYq+gHrlPk3mji0ZU+O+R3VwGvvbZJ/uo1GbGLg1HChHbdThEpYJLXUosL21Z7wsY1DPjlWC0LE8g76wNiBje8u84jPmYwBy37CuupQ8LL9NlYRb+liSjjwhOf2sSTX6Vjbq7B3VNW+70KLrS4M3NNDudHabcQZ6dI7glMI+F8rd6ZSJ1wiVwXSBPSx96vCY4jIzf/HIRBuM1e5tY="
branches:
  only:
    - master