sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "choi15ho@gmail.com"
  - git config --global user.name "YouKnowGit"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "M6WqgRLdmvhMfY00NKBCpKVC4YLber26zie7ih8UPzDF3GG6Ydwgmf6eX7ism+lekFbue/m3uume+7Mvot+Tz/kHSS4CXBIOZsrzsvql0jT4Qppd9Cl2oI1iypgNr05ctenWhgzrhDtd6fwIGA81OrZuTpX5ENo8bOLr9o8geMwxZE
             jeHBp+uqkk3wJjF2LRYZ0nwcsJxSZY6xLKTAAkH2EYpgSxhdpTOhAXp8GalQtoV8dZztArdbfnDBjjyyzeGWq1WnDFuE7DbvivVdRwtwUNPRSV26mhGzLLQPaIvaJMHBB0TD4FWcU5Rw4lQ2sO710qvqLCjtXgwy1ID/aPRQSDo25lGxNe0ly2af8
             ugOa63bQ4XWnY+m9x8YMlhxt2hz6FJSujc/22dMnDQzR1Ja/kgmZv3azOYtDUi8L+jJ52QHLjUUlJQ9Od+AaVv8DbyvDWSJt8WADXrq7qwkEPNuqTIfb2b95W8ntvCv9q5Gvxv08yt+ZT+gN9wvps2CNsjCznN4gAVcyEnniCKIHza3gRrtNvEVnK
             GDSvCKdyjkk+J3V4WcQvUE3dbSWP2qrn8pDuKHm6mkX3J3eszH4FfkMWQE907lS/KrMx7noiFiAs5HxWGq+4/RhP66phrS/OSh5edlBfr+sI+ubRW/nxzcIHRjTmsQYqCbw29KuoRe4="
branches:
  only:
    - master